;;; SPDX-License-Identifier: ISC
;;; Strict JSON reader for the json2dir archive format.

(define-module (json2dir json)
  #:use-module (ice-9 regex)
  #:use-module (srfi srfi-9)
  #:export (parse-json json-object? json-object-entries))

(define-record-type <json-object>
  (make-json-object entries)
  json-object?
  (entries json-object-entries))

(define number-pattern
  (make-regexp "^-?(0|[1-9][0-9]*)(\\.[0-9]+)?([eE][+-]?[0-9]+)?$"))

(define (json-space? char)
  (memv char '(#\space #\tab #\newline #\return)))

(define (decimal->number token match invalid)
  ;; Match serde_json's bounded significand and finite-double range. Guile's
  ;; string->number rejects extreme negative exponents that JSON accepts as
  ;; underflow to zero, so do not pass the raw exponent to that procedure.
  (let ((significand 0) (exponent 0) (overflow? #f))
    (string-for-each
     (lambda (char)
       (let ((next (+ (* significand 10) (- (char->integer char) 48))))
         (if (or overflow? (> next #xffffffffffffffff))
             (begin (set! overflow? #t) (set! exponent (+ exponent 1)))
             (set! significand next))))
     (match:substring match 1))
    (set! overflow? #f)
    (let ((fraction (match:substring match 2)))
      (when fraction
        (string-for-each
         (lambda (char)
           (let ((next (+ (* significand 10) (- (char->integer char) 48))))
             (if (or overflow? (> next #xffffffffffffffff))
                 (set! overflow? #t)
                 (begin (set! significand next) (set! exponent (- exponent 1))))))
         (substring fraction 1))))
    (let ((explicit (match:substring match 3)))
      (when explicit
        (set! exponent (+ exponent (string->number (substring explicit 1))))))
    (let loop ((value (exact->inexact significand)) (exponent exponent))
      (cond
       ((zero? value) 0.0)
       ((> exponent 308) (invalid))
       ((< exponent -616) 0.0)
       ((< exponent -308) (loop (/ value 1e308) (+ exponent 308)))
       (else
        (let* ((power (string->number (string-append "1e" (number->string (abs exponent)))))
               (value (if (negative? exponent) (/ value power) (* value power))))
          (unless (finite? value) (invalid))
          (if (string-prefix? "-" token) (- value) value)))))))

(define (parse-json text)
  "Read exactly one JSON value. Throw json-invalid on malformed input.
Objects have sorted keys, and the last occurrence of a duplicate key wins,
as in the original serde_json implementation. Containers are limited to
127 nested levels, matching serde_json's default recursion limit."
  (let ((position 0) (length (string-length text)))
    (define (invalid)
      (throw 'json-invalid position))
    (define (peek)
      (and (< position length) (string-ref text position)))
    (define (take)
      (let ((char (peek)))
        (unless char (invalid))
        (set! position (+ position 1))
        char))
    (define (expect char)
      (unless (eqv? (take) char) (invalid)))
    (define (skip-space)
      (when (json-space? (peek))
        (take)
        (skip-space)))
    (define (hex-value)
      (let ((char (take)))
        (cond
         ((char<=? #\0 char #\9) (- (char->integer char) 48))
         ((char<=? #\a char #\f) (+ 10 (- (char->integer char) 97)))
         ((char<=? #\A char #\F) (+ 10 (- (char->integer char) 65)))
         (else (invalid)))))
    (define (hex-codepoint)
      (let loop ((remaining 4) (value 0))
        (if (zero? remaining)
            value
            (loop (- remaining 1) (+ (* value 16) (hex-value))))))
    (define (unicode-escape)
      (let ((high (hex-codepoint)))
        (cond
         ((<= #xD800 high #xDBFF)
          (expect #\\)
          (expect #\u)
          (let ((low (hex-codepoint)))
            (unless (<= #xDC00 low #xDFFF) (invalid))
            (integer->char (+ #x10000 (* (- high #xD800) #x400)
                             (- low #xDC00)))))
         ((<= #xDC00 high #xDFFF) (invalid))
         (else (integer->char high)))))
    (define (escape)
      (case (take)
        ((#\") #\")
        ((#\\) #\\)
        ((#\/) #\/)
        ((#\b) #\backspace)
        ((#\f) #\page)
        ((#\n) #\newline)
        ((#\r) #\return)
        ((#\t) #\tab)
        ((#\u) (unicode-escape))
        (else (invalid))))
    (define (read-string)
      (expect #\")
      (let loop ((chars '()))
        (let ((char (take)))
          (cond
           ((eqv? char #\") (list->string (reverse chars)))
           ((< (char->integer char) #x20) (invalid))
           ((eqv? char #\\) (loop (cons (escape) chars)))
           (else (loop (cons char chars)))))))
    (define (literal spelling value)
      (string-for-each expect spelling)
      value)
    (define (read-number)
      (let ((start position))
        (let loop ()
          (let ((char (peek)))
            (when (and char (not (json-space? char))
                       (not (memv char '(#\, #\] #\}))))
              (take)
              (loop))))
        (let ((token (substring text start position)))
          (let ((match (regexp-exec number-pattern token)))
            (unless match (invalid))
            (decimal->number token match invalid)))))
    (define (check-depth depth)
      (when (>= depth 128) (invalid)))
    (define (read-object depth)
      (check-depth depth)
      (expect #\{)
      (skip-space)
      (let ((entries (make-hash-table)))
        (define (finish)
          (expect #\})
          (make-json-object
           (sort (hash-map->list cons entries)
                 (lambda (left right) (string<? (car left) (car right))))))
        (if (eqv? (peek) #\})
            (finish)
            (let loop ()
              (unless (eqv? (peek) #\") (invalid))
              (let ((key (read-string)))
                (skip-space)
                (expect #\:)
                (hash-set! entries key (read-value (+ depth 1))))
              (skip-space)
              (case (peek)
                ((#\}) (finish))
                ((#\,) (take) (skip-space) (loop))
                (else (invalid)))))))
    (define (read-array depth)
      (check-depth depth)
      (expect #\[)
      (skip-space)
      (if (eqv? (peek) #\])
          (begin (take) #())
          (let loop ((items '()))
            (let ((items (cons (read-value (+ depth 1)) items)))
              (skip-space)
              (case (peek)
                ((#\]) (take) (list->vector (reverse items)))
                ((#\,) (take) (loop items))
                (else (invalid)))))))
    (define (read-value depth)
      (skip-space)
      (case (peek)
        ((#\{) (read-object depth))
        ((#\[) (read-array depth))
        ((#\") (read-string))
        ((#\t) (literal "true" #t))
        ((#\f) (literal "false" #f))
        ((#\n) (literal "null" 'null))
        (else (read-number))))
    (let ((value (read-value 1)))
      (skip-space)
      (when (peek) (invalid))
      value)))
